"""Standard-library identity gates; hash bytes, never interpret scoring contents.

An independently frozen caller hash is the trust anchor. Rewriting a manifest
alongside its payload cannot update that anchor. This is an engineering guard
against accidental replacement, not protection from a hostile Python runtime or
concurrent filesystem mutation. Run a frozen snapshot with no concurrent writes.
"""
from __future__ import annotations
import hashlib
import json
import os
import re
from pathlib import Path, PurePosixPath

REQUIRED_EPISODE_FILES = frozenset({
    'episode_contract.json', 'episodes_train.jsonl', 'scoring/scoring_train.jsonl'})
REQUIRED_SOURCE_FILES = frozenset({
    'check_connection.py', 'input_identity.py', 'contracts.py', 'text_mask_model.py',
    'base_manifest.json', 'base_snapshot/episode_loader.py',
    'base_snapshot/episode_model.py', 'base_snapshot/native_replay.py',
    'v0_source_manifest.json'})


def require(ok, message):
    if not ok:
        raise ValueError(message)


def sha256(path):
    digest = hashlib.sha256()
    with Path(path).open('rb') as stream:
        for block in iter(lambda: stream.read(1 << 20), b''):
            digest.update(block)
    return digest.hexdigest()


def valid_sha(value):
    return type(value) is str and re.fullmatch('[0-9a-f]{64}', value) is not None


def no_symlinks(path):
    path = Path(os.path.abspath(path))
    for component in (path, *path.parents):
        require(not component.is_symlink(), f'Symlink forbidden: {component}')
    return path


def regular_file(path):
    path = no_symlinks(path)
    require(path.is_file(), f'Missing regular file: {path}')
    return path


def relative_file(root, name):
    require(type(name) is str and bool(name), 'Empty/nonstring identity path')
    relative = PurePosixPath(name)
    require(not relative.is_absolute() and str(relative) == name
            and '..' not in relative.parts and '\\' not in name
            and name not in {'.', ''}, f'Identity path escape/noncanonical: {name}')
    path = regular_file(root.joinpath(*relative.parts))
    require(path.is_relative_to(root), f'Identity path escape: {name}')
    return path


def read_pinned_json(path, expected_sha256):
    require(valid_sha(expected_sha256), 'External expected SHA256 required')
    path = regular_file(path)
    data = path.read_bytes()
    require(hashlib.sha256(data).hexdigest() == expected_sha256,
            f'External manifest SHA256 mismatch: {path.name}')
    # Reject duplicate JSON keys rather than silently retaining the last value.
    def unique_pairs(pairs):
        result = {}
        for key, value in pairs:
            require(key not in result, f'Duplicate JSON key: {key}')
            result[key] = value
        return result
    value = json.loads(data, object_pairs_hook=unique_pairs)
    require(type(value) is dict, 'Manifest must be an object')
    return value


def discovered_files(root, allow_bytecode=False):
    files = set()
    for path in root.rglob('*'):
        require(not path.is_symlink(), f'Symlink forbidden: {path}')
        if allow_bytecode and '__pycache__' in path.relative_to(root).parts:
            require(path.is_dir() or (path.is_file() and path.suffix == '.pyc'),
                    'Only generated bytecode allowed in __pycache__')
            continue
        if path.is_file():
            files.add(path.relative_to(root).as_posix())
        else:
            require(path.is_dir(), f'Nonregular filesystem entry: {path}')
    return files


def verify_manifest_tree(root, manifest_name, expected_sha256, required, *, source=False):
    root = no_symlinks(root)
    require(root.is_dir(), 'Missing identity root')
    manifest = read_pinned_json(relative_file(root, manifest_name), expected_sha256)
    entries = manifest.get('files')
    require(type(entries) is list and bool(entries), 'Nonempty file manifest list required')
    expected = set()
    total = 0
    for entry in entries:
        require(type(entry) is dict and set(entry) == {'path', 'bytes', 'sha256'},
                'Expected path/bytes/sha256 manifest fields')
        name = entry['path']
        path = relative_file(root, name)
        require(name not in expected and name != manifest_name, 'Duplicate/self manifest entry')
        expected.add(name)
        require(type(entry['bytes']) is int and entry['bytes'] >= 0
                and valid_sha(entry['sha256']), 'Invalid file size/hash')
        require(path.stat().st_size == entry['bytes'], f'File size mismatch: {name}')
        require(sha256(path) == entry['sha256'], f'File SHA256 mismatch: {name}')
        total += entry['bytes']
    require(required <= expected, 'Required identity files omitted')
    require(discovered_files(root, allow_bytecode=source) == expected | {manifest_name},
            'Manifest file coverage mismatch (missing or unlisted payload)')
    return {'root': str(root), 'manifest_sha256': expected_sha256,
            'payload_files_verified': len(expected), 'payload_bytes_verified': total,
            'required_files_verified': sorted(required), 'symlinks_allowed': False,
            'semantic_data_read': False}


def verify_source_tree(root, expected_sha256):
    return verify_manifest_tree(root, 'source_manifest.json', expected_sha256,
                                REQUIRED_SOURCE_FILES, source=True)


def verify_episode_tree(root, expected_sha256):
    return verify_manifest_tree(root, 'export_manifest.json', expected_sha256,
                                REQUIRED_EPISODE_FILES)


def verify_episode_binding(identity_manifest, identity_sha256, episodes):
    expected = read_pinned_json(identity_manifest, identity_sha256)
    receipt = verify_episode_tree(episodes, expected.get('episodes_export_manifest_sha256'))
    return expected, receipt
